RANDOM_LOCATION_LATITUDE_FLOAT_BEGIN = 0.00002921  # 单个坐标点位置纬度浮动泛微
RANDOM_LOCATION_LATITUDE_FLOAT_END = 0.00005039
RANDOM_LOCATION_LONGITUDE_FLOAT_BEGIN = 0.00001921  # 单个坐标点位置经度浮动泛微
RANDOM_LOCATION_LONGITUDE_FLOAT_END = 0.00005039
MAX_DISTANCE = 20  # 两坐标点之间最长距离 单位m  超过该距离将自动生成坐标点避免坐标点分布过疏
DISTANCE_MAX_SEARCH_TIME = 5  # 远距离点修饰最大循环次数
RANDOMLOCATION_STRENGETH = False  # 路径随机强,为False时自动根据线路增加随机点
